version: '3'

services:
  api-gateway:
    image: api-gateway
    build:
      context: ./apps/api-gateway
      dockerfile: dockerfile
    container_name: api-gateway
    #depends_on:
    #  - user-services
    #  - video-services
    #  - analytics-service
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/api-gateway/src:/user/src/app/src:z
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - STAGE=local
      - POSTGRES_HOST=host.docker.internal
    restart: "no"